# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Set the working directory to the default Nginx directory
WORKDIR /usr/share/nginx/html

# Copy your HTML files into the Nginx container
COPY . .

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]


